# Generated by Django 4.2.5 on 2023-10-16 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('information_date', models.DateTimeField(auto_now_add=True)),
                ('information_title', models.CharField(max_length=500)),
                ('information', models.TextField()),
            ],
            options={
                'ordering': ['information_date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_firstname', models.CharField(max_length=100)),
                ('patient_contact', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestation_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_creation_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateTimeField()),
                ('patient', models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='patient_managment.patient')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestation_appointments', to='patient_managment.prestation')),
            ],
            options={
                'ordering': ['appointment_creation_date'],
            },
        ),
    ]
