# Generated by Django 4.2.5 on 2024-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='Bonjour', max_length=100, null=True),
        ),
    ]
