# Generated by Django 4.2.5 on 2023-11-30 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('family_health_app', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
